'use client';

import React, { useState, useRef, useCallback, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

// ============================================================================
// VIDEO COMMENTARY COMPONENT
// ============================================================================
// Short-form video commentary for learning modules. Designed to supplement
// scrollytelling content with screen-share clips, pro tips, and context.
//
// Supports:
// - Bunny.net Stream (recommended, $1/mo minimum)
// - Mux (swap in @mux/mux-player-react if needed)
// - Self-hosted MP4s
// - Placeholder mode for development
// ============================================================================

type VideoProvider = 'bunny' | 'mux' | 'self-hosted';

type TopicTag =
  | 'pro-tip'
  | 'deep-dive'
  | 'quick-take'
  | 'behind-the-scenes'
  | 'common-mistake'
  | 'walkthrough';

interface VideoCommentaryProps {
  /** Unique identifier for this video */
  id: string;
  /** Video title - what this clip covers */
  title: string;
  /** Brief description of the video content */
  description?: string;
  /** Duration in human-readable format (e.g., "2:30", "1 min") */
  duration: string;
  /** Topic category for visual badge */
  topic: TopicTag;
  /**
   * Video source configuration:
   * - Bunny: { provider: 'bunny', libraryId: '...', videoId: '...' }
   * - Mux: { provider: 'mux', playbackId: '...' }
   * - Self-hosted: { provider: 'self-hosted', src: '/videos/...' }
   * - Placeholder: undefined (shows placeholder state)
   */
  video?: {
    provider: VideoProvider;
    // Bunny.net Stream
    libraryId?: string;
    videoId?: string;
    // Mux
    playbackId?: string;
    // Self-hosted
    src?: string;
    // Thumbnail (optional, auto-generated by most providers)
    thumbnail?: string;
  };
  /** Optional className for custom styling */
  className?: string;
}

// Topic tag configuration
const TOPIC_CONFIG: Record<TopicTag, { label: string; color: string; bgColor: string; borderColor: string; icon: string }> = {
  'pro-tip': {
    label: 'Pro Tip',
    color: 'text-[#d4a54a]',
    bgColor: 'bg-[#d4a54a]/10',
    borderColor: 'border-[#d4a54a]/30',
    icon: '💡',
  },
  'deep-dive': {
    label: 'Deep Dive',
    color: 'text-purple-400',
    bgColor: 'bg-purple-400/10',
    borderColor: 'border-purple-400/30',
    icon: '🔬',
  },
  'quick-take': {
    label: 'Quick Take',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-400/10',
    borderColor: 'border-cyan-400/30',
    icon: '⚡',
  },
  'behind-the-scenes': {
    label: 'Behind the Scenes',
    color: 'text-blue-400',
    bgColor: 'bg-blue-400/10',
    borderColor: 'border-blue-400/30',
    icon: '🎬',
  },
  'common-mistake': {
    label: 'Common Mistake',
    color: 'text-red-400',
    bgColor: 'bg-red-400/10',
    borderColor: 'border-red-400/30',
    icon: '⚠️',
  },
  'walkthrough': {
    label: 'Walkthrough',
    color: 'text-green-400',
    bgColor: 'bg-green-400/10',
    borderColor: 'border-green-400/30',
    icon: '🚶',
  },
};

/**
 * Generate video embed URL based on provider
 */
function getVideoUrl(video: VideoCommentaryProps['video']): string | null {
  if (!video) return null;

  switch (video.provider) {
    case 'bunny':
      // Bunny.net Stream embed format
      // https://iframe.mediadelivery.net/embed/{libraryId}/{videoId}
      if (video.libraryId && video.videoId) {
        return `https://iframe.mediadelivery.net/embed/${video.libraryId}/${video.videoId}`;
      }
      return null;

    case 'mux':
      // Mux stream format - for iframe fallback
      // Note: For full Mux player, use @mux/mux-player-react instead
      if (video.playbackId) {
        return `https://stream.mux.com/${video.playbackId}.m3u8`;
      }
      return null;

    case 'self-hosted':
      return video.src || null;

    default:
      return null;
  }
}

/**
 * VideoCommentary - Inline video clips for learning content
 *
 * @example
 * // Placeholder (no video yet)
 * <VideoCommentary
 *   id="ideate-prompt"
 *   title="Crafting the Initial Prompt"
 *   description="How to think about what to include in your ideation prompt"
 *   duration="1:45"
 *   topic="pro-tip"
 * />
 *
 * @example
 * // With Bunny.net video
 * <VideoCommentary
 *   id="ideate-prompt"
 *   title="Crafting the Initial Prompt"
 *   duration="1:45"
 *   topic="pro-tip"
 *   video={{
 *     provider: 'bunny',
 *     libraryId: '12345',
 *     videoId: 'abc123',
 *   }}
 * />
 */
export function VideoCommentary({
  id,
  title,
  description,
  duration,
  topic,
  video,
  className = '',
}: VideoCommentaryProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isHovered, setIsHovered] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const topicConfig = TOPIC_CONFIG[topic];
  const videoUrl = getVideoUrl(video);
  const isPlaceholder = !video || !videoUrl;

  const handlePlay = () => {
    if (isPlaceholder) return;
    setIsPlaying(true);
  };

  const handleClose = useCallback(() => {
    setIsPlaying(false);
    // Stop video if it's a native video element
    if (videoRef.current) {
      videoRef.current.pause();
      videoRef.current.currentTime = 0;
    }
  }, []);

  // Handle Escape key to close modal
  useEffect(() => {
    if (!isPlaying) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose();
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isPlaying, handleClose]);

  return (
    <>
      {/* Video Card */}
      <div
        className={`
          group relative overflow-hidden
          bg-[#0d0d12] border border-white/[0.06]
          rounded-2xl transition-all duration-300
          ${!isPlaceholder ? 'cursor-pointer hover:border-white/[0.12] hover:bg-[#0f0f14]' : ''}
          ${className}
        `}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        onClick={handlePlay}
      >
        {/* Thumbnail / Placeholder Area */}
        <div className="relative aspect-video bg-[#0a0a0f] overflow-hidden">
          {isPlaceholder ? (
            // Placeholder state - shows "Video Coming Soon"
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <div className="w-16 h-16 rounded-full bg-white/5 border border-white/10 flex items-center justify-center mb-4">
                <svg
                  className="w-8 h-8 text-zinc-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
              </div>
              <p className="text-zinc-600 text-sm font-medium">Video Coming Soon</p>
              <p className="text-zinc-700 text-xs mt-1">Recording: {title}</p>
            </div>
          ) : (
            // Thumbnail with play button
            <>
              {/* Thumbnail image if provided */}
              {video?.thumbnail && (
                <img
                  src={video.thumbnail}
                  alt={title}
                  className="absolute inset-0 w-full h-full object-cover"
                />
              )}

              {/* Gradient overlay */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />

              {/* Play button */}
              <motion.div
                className="absolute inset-0 flex items-center justify-center"
                animate={{ scale: isHovered ? 1.1 : 1 }}
                transition={{ duration: 0.2 }}
              >
                <div className={`
                  w-16 h-16 rounded-full
                  ${topicConfig.bgColor} ${topicConfig.borderColor} border-2
                  flex items-center justify-center
                  transition-all duration-300
                  ${isHovered ? 'scale-110' : ''}
                `}>
                  <svg
                    className={`w-6 h-6 ${topicConfig.color} ml-1`}
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M8 5v14l11-7z" />
                  </svg>
                </div>
              </motion.div>
            </>
          )}

          {/* Duration badge */}
          <div className="absolute bottom-3 right-3 bg-black/70 backdrop-blur-sm px-2 py-1 rounded text-xs text-zinc-300 font-mono">
            {duration}
          </div>

          {/* Topic badge */}
          <div className={`
            absolute top-3 left-3
            ${topicConfig.bgColor} ${topicConfig.borderColor} border
            backdrop-blur-sm px-2 py-1 rounded-full
            flex items-center gap-1.5
          `}>
            <span className="text-sm">{topicConfig.icon}</span>
            <span className={`text-xs font-medium ${topicConfig.color}`}>
              {topicConfig.label}
            </span>
          </div>
        </div>

        {/* Content */}
        <div className="p-4">
          <h4 className="font-semibold text-white text-sm mb-1 line-clamp-1">
            {title}
          </h4>
          {description && (
            <p className="text-zinc-500 text-xs line-clamp-2">
              {description}
            </p>
          )}
        </div>
      </div>

      {/* Video Modal */}
      <AnimatePresence>
        {isPlaying && videoUrl && (
          <motion.div
            className="fixed inset-0 z-50 flex items-center justify-center p-4 md:p-8"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={handleClose}
          >
            {/* Backdrop */}
            <div className="absolute inset-0 bg-black/90 backdrop-blur-sm" />

            {/* Video container */}
            <motion.div
              className="relative w-full max-w-4xl aspect-video bg-black rounded-xl overflow-hidden shadow-2xl"
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              transition={{ type: 'spring', damping: 25, stiffness: 300 }}
              onClick={(e) => e.stopPropagation()}
            >
              {/* Close button */}
              <button
                onClick={handleClose}
                className="absolute top-4 right-4 z-10 w-10 h-10 rounded-full bg-black/50 border border-white/10 flex items-center justify-center text-white hover:bg-black/70 transition-colors"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>

              {/* Video player */}
              {video?.provider === 'bunny' ? (
                // Bunny.net iframe embed
                <iframe
                  ref={iframeRef}
                  src={`${videoUrl}?autoplay=true`}
                  className="w-full h-full"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                />
              ) : video?.provider === 'self-hosted' ? (
                // Native video element for self-hosted
                <video
                  ref={videoRef}
                  src={videoUrl}
                  className="w-full h-full"
                  controls
                  autoPlay
                  playsInline
                />
              ) : video?.provider === 'mux' ? (
                // Mux - for now use HLS.js or recommend @mux/mux-player-react
                <div className="flex items-center justify-center h-full text-zinc-400">
                  <p>For Mux videos, install @mux/mux-player-react</p>
                </div>
              ) : null}

              {/* Title overlay */}
              <div className="absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-black/80 to-transparent">
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-sm ${topicConfig.color}`}>{topicConfig.icon}</span>
                  <span className={`text-xs font-medium ${topicConfig.color}`}>{topicConfig.label}</span>
                </div>
                <h3 className="text-white font-semibold">{title}</h3>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

/**
 * VideoCommentaryGrid - Display multiple videos in a responsive grid
 */
interface VideoCommentaryGridProps {
  children: React.ReactNode;
  columns?: 1 | 2 | 3;
  className?: string;
}

export function VideoCommentaryGrid({
  children,
  columns = 2,
  className = '',
}: VideoCommentaryGridProps) {
  const gridCols = {
    1: 'grid-cols-1',
    2: 'grid-cols-1 md:grid-cols-2',
    3: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
  };

  return (
    <div className={`grid ${gridCols[columns]} gap-4 ${className}`}>
      {children}
    </div>
  );
}

export default VideoCommentary;
